"""
Given any initial natural number, consider the sequence of numbers generated by repeatedly following the rule:

    * divide by two if the number is even or
    * multiply by 3 and add 1 if the number is odd

"""

def init(start):
    global n 
    n = start
    print "start value:", n
    
def apply_to_n(val):
    global n 
    if n%2 == 0: n = n/2
    else: n=n*3+1
    
def compute():
    
    max_val = None
    
    while (n !=  1):
        
        if max_val is None:  max_val = n
        else:
            if n > max_val: max_val = n
            
        print n
        apply_to_n(n)
    
    else: print n
    
    print "Max value: ", max_val
    
init(217)
compute()